<?php
namespace app\index\controller;
use think\Controller;
use think\Session;

class Base extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        define("USER_ID",Session::has("user_info.id") ? Session::get("user_info.id"):null);
    }
    public function isLogin(){
        if(is_null(USER_ID)){
            $this->error('用户未登陆,无权访问',url('user/login'));
        }
    }
    public function alerdyLogin(){
        if(USER_ID){
//            $this->error('用户已经登陆,请勿重复登陆',url('index/index'));
            echo '<script>window.close();</script>';
        }
    }
}
